#spring.application.name=news
server:
  port: 8080
  servlet:
    context-path: /news_lv
    session:
      timeout: 1440m  # Thời gian session là 1440 phút (1 ngày)

cloudinary:
  cloud-name: dd1grolgr
  api-key: 165223227289875
  api-secret: KuEgKknBTrJ7-FdsAHGJYa_Jx4c

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/news_lv"
    username: root
    password: khang78780213

  jpa:
    hibernate:
      ddl-auto: update
      #ddl-auto: none
    #show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 40923801016-6nrv9qjs1iut9vle1r1s24fms86449s0.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  #Khai báo thymeleaf
  mvc:
    static-path-pattern: /static/**
  #thymeleaf:
    #prefix: classpath:/templates/
    #suffix: .html