#spring.application.name=news
server:
  port: 8080
  servlet:
    context-path: /news_lv
    session:
      timeout: 1440m  # Thời gian session là 1440 phút (1 ngày)

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/news_lv"
    username: root
    password: khang78780213

  jpa:
    hibernate:
      ddl-auto: update
      #ddl-auto: none
    #show-sql: true

  #Khai báo thymeleaf
  mvc:
    static-path-pattern: /static/**